services:
  
  catalogdb:
    image: postgres
  
  basketdb:
    image: postgres
  
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile
volumes:
  postgres_catalog:
  postgres_basket:
